### ISSUE TITLE
UnivariateSpline: interpolator(a) raises error, but interpolator.integrate(a,b) does not

### ISSUE THREAD

**Issue by oceanEngineer** [scipy/scipy.org#101]
I would like to create an interpolator which also integrates. The UnivariateSpline class seems like a simple solution to this problem. 

My problem is that I would like it to return nan values outside of the bbox range. I came up with a solution involving a try/except statement. This works for the original interpolator function, but not for its integral (!)

My hacky solution is to evaluate the interpolator to catch the error, but then evaluate the integral. This seems like a bug to me though, so I thought I would report it. 

At the same time, I will ask if there is a better way to perform this operation.

```
x=np.r_[0:10:10j]
interpolator=UnivariateSpline(x, x, k=1, ext=2)
xNew=np.r_[5:15:10j]

integral=[]
for d in xNew:
    # fill extrapolated values with nan
    try:
        _=interpolator(d)
        integral.append(interpolator.integral(0,d))
    except ValueError:
        integral.append(np.nan)
```

**Comment by pv** [comment]
Note that this is the wrong issue tracker for this --- the correct one
to use is at https://github.com/scipy/scipy/
