### ISSUE TITLE
Wiki and blogs are down (again)

### ISSUE THREAD

**Issue by DhrubajyotiDas** [scipy/scipy.org#102]
Currently, neither http://wiki.scipy.org/ nor http://planet.scipy.org/ can be accessed.

Same issue as this one: https://github.com/scipy/scipy.org/issues/85

**Comment by takluyver** [comment]
I've pinged people by email, but no response yet. I'll ping again.

**Comment by argriffing** [comment]
"It's not just you! http://mail.scipy.org looks down from here."

**Comment by filipesaraiva** [comment]
It is down yet :(

**Comment by eternia478** [comment]
Mailing list is also acting up, with weird things like 

<code>
<scipy-dev-scipy.org@scipy.org> (expanded from <scipy-dev@scipy.org>): unknown user: "scipy-dev-scipy.org"
</code>

Not sure if related. Also, http://mail.scipy.org and http://planet.scipy.org are directed to MPI for Python, which doesn't make sense. wiki is completely down.

**Comment by Naereen** [comment]
Wiki is still down, no-one has any idea how to fix that?

**Comment by pv** [comment]
xref https://github.com/numpy/numpy/issues/6325

**Comment by fkbreitl** [comment]
Same thing here. My bug reports were all closed.

**Comment by imranal** [comment]
The http://wiki.scipy.org/ is still down. I can't access it.

**Comment by rcoacci** [comment]
Is there any place where we can find the wiki content while it's down? Internet Archive has nothing, since the wiki had a restrictive robots.txt

**Comment by Naereen** [comment]
I tried too, and Google cache, and other web crawler caches, *nothing* :cry: !

**Comment by argriffing** [comment]
@rcoacci @Naereen Just out of curiosity, were you guys looking for the 'numpy for matlab users' page?

**Comment by rcoacci** [comment]
Nope, but there are lots of really useful pages there like Cookbook and ParalellProgramming. I'm specifically after the second.

**Comment by Naereen** [comment]
@argriffing yes!
I found [that one instead](http://mathesaurus.sourceforge.net/matlab-numpy.html), but it's somehow not as useful :disappointed: ...

**Comment by argriffing** [comment]
Th mailing list has some [discussion](https://mail.scipy.org/pipermail/scipy-dev/2015-October/021012.html) about this, and at least some of the content is temporarily [rehosted](http://pav.iki.fi/tmp/to-be-removed/localhost_8080/NumPy_for_Matlab_Users.html).

**Comment by imranal** [comment]
I want to access the cookbook. It seems that the content has been inaccessible for almost a month now.

**Comment by argriffing** [comment]
> I want to access the cookbook. 

According to that mailing list thread, the cookbook has been converted to IPython notebooks at http://pv.github.io/SciPy-CookBook/.

**Comment by imranal** [comment]
I can't seem to find the Cython LIC example (Line integral convolution). 

Perhaps also a good idea to change the link to cookbook at http://scipy.org/

**Comment by gsogc** [comment]
i need mirror site.

**Comment by Naereen** [comment]
Some important pages from the dead ``wiki.scipy.org`` are now hosted here: https://docs.scipy.org/doc/numpy-dev/user/
For instance, [Numpy for MATLAB users](https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html).

And the CookBook is now at https://scipy-cookbook.readthedocs.org/.

**Comment by pv** [comment]
Seems to have been sorted out.

**Comment by Naereen** [comment]
Well, the wiki is still not available.
The pages can be read from https://scipy.github.io/old-wiki/pages/ though, it might be enough for now.

**Comment by pv** [comment]
`wiki.scipy.org` redirects to those pages. The wiki itself is not going to come back --- it was edited 2 times in the last 2 years.

**Comment by WarrenWeckesser** [comment]
>  ... it was edited 2 times in the last 2 years.

Was is even working?  I tried editing it a year ago (https://mail.scipy.org/pipermail/scipy-dev/2014-December/020259.html) and wasn't able to.

**Comment by pv** [comment]
Iirc, it was in read-only mode for the last 2-3 years, due to being spammed to halt. The other numbers were 95 edits in the last 5 years. Nevertheless, if a wiki is needed (which is not clear), the hosting/maintenance should be done in a way that does not depend on piggybacking on someone's goodwill or available free time.

**Comment by Naereen** [comment]
OK.
Then it's settled, this issue is indeed fixed.

Thanks for the explanations :tophat: !
