### ISSUE TITLE
Error in numpy.random.gumbel doc examples

### ISSUE THREAD

**Issue by as79** [scipy/scipy.org#106]
In the second example code at 

http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.gumbel.html 

The following line 

beta = np.std(maxima)*np.pi/np.sqrt(6)

should be

beta = np.std(maxima) * np.sqrt(6) / np.pi

Rgds

**Comment by argriffing** [comment]
Thanks for the report, this should be in scipy/scipy instead of scipy/scipy.org.

**Comment by WarrenWeckesser** [comment]
Actually, this is about `numpy.random.gumbel`, so the issue should be reported at https://github.com/numpy/numpy/issues

**Comment by argriffing** [comment]
oops!
