### ISSUE TITLE
scipy.optimize.basinhopping: accept_test returning numpy.bool_ raises an error

### ISSUE THREAD

**Issue by dEvasEnApati** [scipy/scipy.org#122]
Dear Scipy team

When using scipy.optimize.basinhopping, if the accept_test function returns an object of type numpy.bool_, an error occurs. Is this an intentional feature? If not, I think it can be removed allowing accept_test to return numpy.bool_ object.

Thanks
Ajay

**Comment by pv** [comment]
Note that this is the bug tracker for the website, please use the one for the library: https://github.com/scipy/scipy/issues/
