### ISSUE TITLE
MathJax fails to load, due to mixed content rules

### ISSUE THREAD

**Issue by mrhmouse** [scipy/scipy.org#127]
In Firefox 23 & above (and possibly other browsers), pages served over HTTPS will refuse to load content served over HTTP. Since MathJax is loaded over HTTP in the documentation, formulas fail to render.

For example, see this page: https://docs.scipy.org/doc/scipy/reference/tutorial/linalg.html#decompositions

**Comment by pv** [comment]
Has been addressed.

**Comment by mrhmouse** [comment]
Wonderful, thank you! :cake:
