### ISSUE TITLE
Overloaded ‘isnan(double&)’ is ambiguous when compiling with gcc 4.8.1 -std=c++11

### ISSUE THREAD

**Issue by tyhone** [scipy/scipy.org#130]
This may be a numpy issue rather than a scipy issue, nevertheless, when installing scipy with the command "sudo -H pip install" I get the following compilation error:

In file included from scipy/special/Faddeeva.cc:122:0:
scipy/special/Faddeeva.cc: In function ‘std::complex<double> Faddeeva::erf(std::complex<double>, double)’:
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_math.h:171:41: error: call of overloaded ‘isnan(double&)’ is ambiguous

System details:
Ubuntu 12.04.2 LTS 
gcc (Ubuntu 4.8.1-2ubuntu1~12.04) 4.8.1
numpy.__version__ = '1.10.1'

It appears numpy is trying to use the math.h version of isnan.  I suspect somewhere else in the build process cmath.h has also been included resulting in the ambiguity.

**Comment by pv** [comment]
Note that the correct issue tracker is here: https://github.com/scipy/scipy/issues
