### ISSUE TITLE
Unused variable declaration in generated f2pywrappers2

### ISSUE THREAD

**Issue by wtjones1** [scipy/scipy.org#132]
I am using f2py for a project where the coding standards forbid the declaration of unused variables.  This is enforced by automated builds which consider warnings as errors.  As such, I am prevented from successfully compiling the *-f2pywrappers2.f90 code due to the declaration of an unused variable.

The variable "j" is declared in the wrappers generated to provide the dimensions of arrays.  The declaration comes in the form of "integer r,i,j" but "j" is never used.  I have tracked this down to "numpy/f2py/f90mod_rules.py", specifically line 52 in numpy version 1.10.2, in the definition of "fgetdims1".  The declaration seems to have existed since at least numpy version 1.4.1.  Removal of the declaration of "j", while leaving "r" and "i", eliminates the unused variable warnings.

**Comment by ev-br** [comment]
We do not ship f2py, it's numpy: https://github.com/numpy/numpy
