### ISSUE TITLE
error in numpy mask doc

### ISSUE THREAD

**Issue by sunchaoatmo** [scipy/scipy.org#135]
In http://docs.scipy.org/doc/numpy/reference/maskedarray.generic.html#the-numpy-ma-module
Indexing and slicing, the example is:
>>> x = ma.array([1, 2, 3, 4, 5], mask=[0, 1, 0, 0, 1])
>>> mx = x[:3]
>>> mx
masked_array(data = [1 -- 3],
             mask = [False  True False],
       fill_value = 999999)
>>> mx[1] = -1
>>> mx
masked_array(data = [1 -1 3],
             mask = [False  True False],
       fill_value = 999999)

However, for mx, given we assigned mx[1] as -1 ,so the output is supposed to be unmasked for mx[1]. I tested it with Python 2.7.11, here is the output:

>>> import numpy.ma as ma
>>> x = ma.array([1, 2, 3, 4, 5], mask=[0, 1, 0, 0, 1])
>>> mx = x[:3]
>>> mx
masked_array(data = [1 -- 3],
             mask = [False  True False],
       fill_value = 999999)

>>> mx[1] = -1
>>> mx
masked_array(data = [1 -1 3],
             mask = [False False False],
       fill_value = 999999)

**Comment by argriffing** [comment]
I think this doc file is in the numpy repo, https://github.com/numpy/numpy/blob/master/doc/source/reference/maskedarray.generic.rst

**Comment by pv** [comment]
Please report this issue here: https://github.com/numpy/numpy/issues
