### ISSUE TITLE
Bounds not respected in scipy.optimize.minimize?

### ISSUE THREAD

**Issue by cfcohen** [scipy/scipy.org#139]
The following code did not produce the results that I expected.   I don't know whether it's a bug or not, but I suspect that it is.  Problematically (for me at least), the behavior is very different when undefined is set to None, 0.0, 1.0, etc.   I expected that the bounds parameter would ensure that f(x) was not invoked with an invalid value of x.  SLSQP is not the only minimizer that exhibits this problem, and other on the Internet appear to have received similar results.

```python
import scipy.optimize
undefined = None
def f(x):
    if x > 1.0:
        print("x > 1.0, x=%12.10f" % x)
        return undefined
    print("f(%f)=1.0" % x)
    return 1.0
# The bounds are not properly respected!
print scipy.optimize.minimize(f, 1.0, method='SLSQP', bounds=[(0.0, 1.0)])
```

I don't necessarily expect a fix, I just wanted to report the issue.

**Comment by takluyver** [comment]
This is the repo for the Scipy website - the repo for Scipy itself is here:
https://github.com/scipy/scipy
