### ISSUE TITLE
scipy-svn mailing list?

### ISSUE THREAD

**Issue by pv** [scipy/scipy.org#144]
The https://mail.scipy.org/mailman/listinfo/scipy-svn mailing list seems to be not accepting mails sent to it from Github. The similar list https://mail.scipy.org/mailman/listinfo/numpy-svn on the other hand is accepting mail.

**Comment by rgommers** [comment]
Is that still needed? It seems like some arcane way of backing up an SVN server that's not really needed anymore with Git.

**Comment by pv** [comment]
If you want notifications about merges, similarly as it was for commits to svn. It's also a public record of pushes to git and corresponding commit hashes, which are not really tracked in git (apart from people's own cloned repos).

**Comment by rgommers** [comment]
Okay, clear.

**Comment by gfyoung** [comment]
+1 for such a mailing list.  I find it to be quite useful in `numpy`, and I see no reason why `scipy` wouldn't benefit from it either.

**Comment by pv** [comment]
Closing, not going to happen now that we don't host mailing lists any more.
