### ISSUE TITLE
Update Building From Source on Windows

### ISSUE THREAD

**Issue by gfyoung** [scipy/scipy.org#145]
Placing issue in `scipy.org` that can then be closed by my PR.  Links to `numpy` issue <a href="https://github.com/numpy/numpy/issues/5479">#5479</a> and <a href="https://github.com/numpy/numpy/issues/7104">#7104</a>.

**Comment by takluyver** [comment]
Did you mean to open this on [scipy/scipy](https://github.com/scipy/scipy)? This repo is for the scipy.org website.

**Comment by takluyver** [comment]
Never mind, I see your PR. Should have looked more carefully.
