### ISSUE TITLE
Please update the Debian version in the install page

### ISSUE THREAD

**Issue by KamarajuKusumanchi** [scipy/scipy.org#154]
The "Ubuntu & Debian" section of http://www.scipy.org/install.html page refers to Debian 7.0 which is an old version. The current stable Debian version is 8.3 and was released on Jan 23rd, 2016 [1]. Could you please update the page accordingly?

[1] - https://www.debian.org/releases/stable/

**Comment by gfyoung** [comment]
This page definitely needs a make-over, as that is not the only thing that is outdated on this page.  I recently did a good amount of work to update various portions of this website, so I can certainly try to do some updating on this page as well.
