### ISSUE TITLE
matrix multiplication goes wrong

### ISSUE THREAD

**Issue by LSChyi** [scipy/scipy.org#161]
I tried to multiply two matrix, but the result is wrong.
Here is the instance I used:

public_base = np.matrix([[-1612927239, 1853012542, 1451467945], [-2137446623, 2455606985, 1923480029], [2762180674, -3173333120, -2485675809]])
original_signature = np.matrix([[87398273893], [763829184], [118237397273]])
point = public_base * original_signature

and the answer I got is
[[-4827367651133834946]
 [ 5600303079090794586]
 [  426332741103555793]] 

but since the correct answer is 

1.0e+19 *

   3.2066
   4.2494
   -5.4914

**Comment by pv** [comment]
The answer is that the result you got is for 64-bit integer matrices.
Please see the documentation or ask on stackoverflow for more.
