### ISSUE TITLE
Typo on website

### ISSUE THREAD

**Issue by msustik** [scipy/scipy.org#164]
On http://docs.scipy.org/doc/scipy/reference/sparse.linalg.html

one finds:

"Return a fuction for solving a sparse..."

Best,
-Matyas

**Comment by takluyver** [comment]
Thanks. The docs aren't part of this repo, however. That line is actually generated from a docstring in the code:
https://github.com/scipy/scipy/blob/3d2e725f9856a273d45ba85d9aa7cb01fc559ac6/scipy/sparse/linalg/dsolve/linsolve.py#L328
