### ISSUE TITLE
scipy.sparse.coo_matrix.tocsr modifies the row, col, and data attributes of the original coo_matrix

### ISSUE THREAD

**Issue by michaelbynum** [scipy/scipy.org#175]
In scipy-0.18.0, scipy.sparse.coo_matrix.tocsr() modifies the row, col, and data attributes of the original matrix. This is not the case in scipy-0.17.0. Consider the following example:

***************************************************************************************
import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg

row = [0, 1, 2, 0, 0, 1, 2, 3, 4, 5, 3, 4, 5, 6, 7, 6, 7, 6, 7]
col =[3, 4, 5, 7, 6, 7, 6, 0, 1, 2, 3, 4, 5, 2, 0, 0, 1, 6, 7]
data = [-1,    -1,    -1,    -1,     1,     1,    -1,     0,     0,     1,     1,     1,     0,    -1,    -1,     1,     1,     0.491,  0.491]

A = scipy.sparse.coo_matrix((data, (row,col)), shape=(8,8))
print A.toarray()

print A.row
print A.col
print A.data

B = A.tocsr()

print A.row
print A.col
print A.data

print A.toarray()

****************************************************************************************

In both 0.17.0 and 0.18.0, the matrix A does not change. However in 0.18.0, A.row, A.col, and A.data chage after A.tocsr() is called. This is problematic when, for example, I need to create A, convert to csr, solve a linear system, update only the data of A, repeat.

Scipy has been a tremendous asset to my work, so I'd like to thank the development team. Also, thanks for help with this issue.

**Comment by takluyver** [comment]
This repository is for the Scipy.org website - please report issues in Scipy itself here:
https://github.com/scipy/scipy/issues

**Comment by michaelbynum** [comment]
Oh, I apologize.

**Comment by takluyver** [comment]
No problem
