### ISSUE TITLE
Invalid link to RecordArrays in Quickstart Tutorial

### ISSUE THREAD

**Issue by scimax** [scipy/scipy.org#176]
I hope this is the right place to submit this issue.

While browsing the [Quickstart Guide](http://docs.scipy.org/doc/numpy/user/quickstart.html#fancy-indexing-and-index-tricks) in the "Fancy Indexing" section I found this [link](http://docs.scipy.org/doc/numpy/user/RecordArrays.html) under "Indexing with Strings" which is pointing nowhere.
Should it point to this [section](http://docs.scipy.org/doc/numpy/user/basics.rec.html#record-arrays)?

**Comment by pv** [comment]
The link is in the numpy documentation, so the numpy issue tracker is 
the right place to report it (so that you reach the relevant people).

**Comment by scimax** [comment]
Ah, ok, sorry, thank you for your advice. I think [this](https://github.com/numpy/numpy/blob/1429c606643d1ad305e710c4a31cb6f398d04c53/doc/source/user/quickstart.rst) is the place of the source. I will submit the issue there.
Closed.
