### ISSUE TITLE
Can't load scipy.org ?

### ISSUE THREAD

**Issue by jakirkham** [scipy/scipy.org#187]
Appears I'm completely unable to load scipy.org or any other related pages or links from Google. I keep getting "The connection was reset" errors from Firefox. Have already tried clearing my cache and it made no difference. Safari simply fails to load the page at all. Chrome gives me "ERR_EMPTY_RESPONSE". Is there some kind of known outage that is going on?

**Comment by matthew-brett** [comment]
Same for me and http://downforeveryoneorjustme.com/scipy.org

**Comment by matthew-brett** [comment]
Still down.

**Comment by rgommers** [comment]
@dpinte as per email: ping.

**Comment by rgommers** [comment]
Short summary: currently both scipy.org and docs.scipy.org are unreachable. Those live on different servers, and I can ssh into both servers just fine. So something else is going on - certificates, DNS stuff?

**Comment by skirpichev** [comment]
> I can ssh into both servers just fine

SSH is on:
```
$ nc scipy.org 22
SSH-2.0-OpenSSH_5.5p1 Debian-6+squeeze8
^C
```

> So something else is going on - certificates, DNS stuff?

To me, it seems the webserver is down or connections are filtered:
```
$ nc scipy.org 80
scipy.org [50.17.248.72] 80 (http) : Connection refused
```

**Comment by pv** [comment]
They are the same server in fact. However, I understand someone is looking at this so it hopefully gets resolved soon.

**Comment by aterrel** [comment]
Do we know who is looking into it? Didrik is on vacation away from computers for the rest of the week (or that's what he told me).

**Comment by pv** [comment]
Afaik their IT guy is aware of the issue.

**Comment by aterrel** [comment]
Okay great! That's the right person.

**Comment by pv** [comment]
Ok, I got roots and fixed it. Should be back up now.

**Comment by rgommers** [comment]
Thanks Pauli!

**Comment by Araneidae** [comment]
Seems to be down again this morning.

**Comment by rgommers** [comment]
Thanks for the report @Araneidae. Tracking issue for this new problem is https://github.com/numpy/numpy/issues/8779
