### ISSUE TITLE
LaTeX rendering broken

### ISSUE THREAD

**Issue by englandschorsch** [scipy/scipy.org#191]
The LaTeX rendering on this site:
https://docs.scipy.org/doc/scipy-0.16.0/reference/tutorial/linalg.html
seems to be broken. I tested it with both Firefox and Chrome, but all i see is the raw LaTeX code.

**Comment by person142** [comment]
It looks fixed in recent versions:

https://docs.scipy.org/doc/scipy-0.18.1/reference/tutorial/linalg.html

Also, a note: the correct bug tracker for this is https://github.com/scipy/scipy/issues.

**Comment by englandschorsch** [comment]
Oh sorry, I did not realize that my Google research had led me to a deprecated version of the website.

Concerning the bug tracker, I have to say that I merely followed the bug tracker link from https://www.scipy.org/bug-report.html, where it says "For problems with this scipy.org website, use the bug tracker for the scipy.org website project." This led me here. Maybe a more precise link would be advisible?

Thanks a lot for your help,
Schorsch

**Comment by pv** [comment]
It says "Please report bugs, documentation errors etc. in the following 
trackers:" above. However, maybe adding "For problems with this 
scipy.org website (but not on docs.scipy.org), use the bug tracker ..."

**Comment by takluyver** [comment]
I've opened #192 to try to make it clearer.
