### ISSUE TITLE
is docs.scipy.org down?

### ISSUE THREAD

**Issue by acochrane** [scipy/scipy.org#198]
I can't reach https://docs.scipy.org

Is it just me?

**Comment by xelibrion** [comment]
@acochrane nope, it's down for me too

**Comment by Akarius** [comment]
Still down for me.

**Comment by rahulporuri** [comment]
please ref https://github.com/numpy/numpy/issues/8779#issuecomment-286361802

**Comment by acochrane** [comment]
Looks good guys!
