### ISSUE TITLE
scipy.org not updating, served from the wrong location?

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy.org#204]
The last few PRs have been pushed to the scipy.org server; I see that the files in ``/srv/scipy_org`` are up-to-date. They're not being served however, an outdated copy is (and checked that it's not my browser cache). There seem to be 4 copies of the site floating around, in:

    /mnt/scipy300/srv/scipy_org/
    /srv/scipy_org/
    /var/www/html/
    /var/www/html/scipy_org_tmp/

Not sure what's going on there. @dpinte any idea?

**Comment by Fleetside58** [comment]
Ralf I had to use /var/www/html/, so you're welcome to push updates to that directory and trash the other three. For whatever reason, I couldn't get Apache to serve from /srv/scipy_org/ per the config of the old box.

**Comment by rgommers** [comment]
Thanks @Fleetside58. I don't have permissions for ``/var/www/html`` though. There's some ``setgid``/``setuid`` thing that needs to be done (@dpinte did that last week for ``/srv/scipy_org``), so this works for non-admin users:

    rsync -org --chown=www-data:www-data --delete-after --exclude '.git' _build/html/ USERNAME@scipy.org:/var/www/html/

Could you do that?

**Comment by Fleetside58** [comment]
For which _USERNAME_?

**Comment by rgommers** [comment]
Any account name on the scipy.org server with ssh access should be able to run that (it's part of the [Makefile for scipy.org](https://github.com/scipy/scipy.org/blob/master/www/Makefile)).

**Comment by Fleetside58** [comment]
I ran this command:
`sudo rsync -org --chown=www-data:www-data --delete-after --exclude '.git' _build/html/ cholton@scipy.org:/var/www/html/`

and got these errors:
```
ssh: connect to host scipy.org port 22: Connection timed out 

rsync: connection unexpectedly closed (0 bytes received so far) [sender] 

rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.1]
```
One or both of us doesn't have the whole picture.

**Comment by rgommers** [comment]
Fixed by @dpinte changing the permissions on ``/var/www/html`` and by serving both scipy.org and www.scipy.org from that directory.

Updated Makefile for that in gh-205.

Re "ran this command": it's not supposed to be run on the server. You run it in the ``www`` directory of your local copy of this repo.

**Comment by rgommers** [comment]
Thanks for the help @Fleetside58 and @dpinte
