### ISSUE TITLE
pip works on windows 10

### ISSUE THREAD

**Issue by videlec** [scipy/scipy.org#207]
I successefully install numpy + matplotlib + jupyter on Windows 10 using directly pip shipped with Python 3.6.1. However, this option is not mentioned on the website and is by far the simplest (and cheapest in memory). More precisely, in the "Installing via pip" it is written

    Mac and Linux users can install pre-built binary packages for the SciPy
    stack using pip. Pip can install pre-built binary packages in the wheel
    package format.

and, at least in my case, the same procedure went fine on Windows 10. The procedure I used

1. Install the official Python 3.6.1 (allowing the installer to modify the PATH) 
2. Open the windows command line (via Windows+x -> execute -> cmd) and run

    > pip install numpy
    > pip install matplotlib

I did not even use the wheels from Christoph Gohlke mentioned in the section "Windows Packages".

(Sided note: "pip install jupyter" also went fine.)

**Comment by pv** [comment]
You cannot install all of the core packages via pip.

**Comment by takluyver** [comment]
Specifically, scipy does not appear to have Windows wheels on PyPI at present.

**Comment by videlec** [comment]
@pv @takluyver Thanks for your answers. What does prevent having the wheels on PyPI?

**Comment by ev-br** [comment]
See e.g., https://github.com/scipy/scipy/issues/5461 for the Windows wheels
