### ISSUE TITLE
No permissions to update docs.scipy.org

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy.org#213]
The content at http://docs.scipy.org/ is served from ``/srv/docs_scipy_org/doc/``, which doesn't have the correct permissions for me to update it (and probably the same for the other user accounts). 

This is very similar to gh-204. @Fleetside58, @dpinte could one of you have a look?

Permissions should be like for ``/var/www/html/``, which is where http://scipy.org content is served from:

    $ ls -l /var/www/html
    total 312
    -rw-rw-r-- 1 rgommers www-data  10463 Jun  8 10:54 about.html
    -rw-rw-r-- 1 rgommers www-data   8684 Jun  8 10:54 bug-report.html
    -rw-rw-r-- 1 rgommers www-data  15810 Jun  8 10:54 citing.html
    ...

    rgommers@www:/var/www/html$ ls -l /srv/docs_scipy_org/doc/
    total 16676
    drwxr-xr-x  2 root root    4096 Mar 13 18:01 dev
    -rw-r--r--  1 root root    3706 Mar 13 18:01 download.html
    -rw-r--r--  1 root root  404489 Mar 13 18:01 error.html
    drwxr-xr-x  2 root root    4096 Mar 13 18:01 external
    drwxr-xr-x  2 root root   20480 Mar 13 18:03 _images
    -rw-r--r--  1 root root   15690 Mar 13 18:01 index.html
    lrwxrwxrwx  1 root root      12 Mar 13 18:01 numpy -> numpy-1.12.0
    ....

**Comment by dpinte** [comment]
@rgommers looking at it now!

**Comment by dpinte** [comment]
@rgommers can you try now? Permissions have been updated.

**Comment by rgommers** [comment]
Thanks, that worked!
