### ISSUE TITLE
Numpy v.1.13 TypeError with scipy.misc.pilutil.imsave of binary images

### ISSUE THREAD

**Issue by deathsta1ker** [scipy/scipy.org#215]
Received the following error:

```
Traceback:
[...]
  File "~/lib/python3.6/site-packages/scipy/misc/pilutil.py", line 197, in imsave
    im = toimage(arr, channel_axis=2)
  File "~/lib/python3.6/site-packages/scipy/misc/pilutil.py", line 299, in toimage
    cmin=cmin, cmax=cmax)
  File "~/lib/python3.6/site-packages/scipy/misc/pilutil.py", line 94, in bytescale
    cscale = cmax - cmin
TypeError: numpy boolean subtract, the `-` operator, is deprecated, 
use the bitwise_xor, the `^` operator, or the logical_xor function instead.
```

when trying to save a binary image (`np_array = np_array.astype('bool')`) to file with scipy.misc's imsave (using scipy v.0.19.0).

To produce the error, I used scipy.misc's `imread` to open a color TIFF. I used the standard luminosity conversion to turn the color image to grayscale and Otsu's method to turn the grayscale image to binary. The error came when I tried to save the image to file. 

I don't want to have to manually convert the bool arrays to uint8 and then multiply the 1's by 255 (if I can help it). For now, I can work around this error by reinstalling scipy using numpy v.1.11.3 or numpy v.1.12.1.

**Comment by perimosocordiae** [comment]
This is the wrong issue tracker. Please open this again at https://github.com/scipy/scipy/issues
