### ISSUE TITLE
Scipy Central link is dead

### ISSUE THREAD

**Issue by jchoude** [scipy/scipy.org#225]
When viewing most pages of the scipy.org website, in the right sidebar, there is a link to "Scipy central".

However, this link currently points to http://central.scipy.org/ , which seems to be dead.

**Comment by rgommers** [comment]
Thanks @jchoude. We've discussed it at https://github.com/scipy/SciPyCentral/issues/207 and looks like we're going to remove the links soon. I think I'll do it right now actually.
