### ISSUE TITLE
planet.scipy.org is down

### ISSUE THREAD

**Issue by itamarst** [scipy/scipy.org#263]
Times out when I try to connect to it.

**Comment by pv** [comment]
@GaelVaroquaux: ping

**Comment by itamarst** [comment]
And it's back! Thanks to whoever fixed it.

**Comment by itamarst** [comment]
And now it's timing out again :cry:

**Comment by pv** [comment]
Back up now.

**Comment by GaelVaroquaux** [comment]
Very cool Pauli! I am glad that you had some form of backup (did you use
Google's cache?)

**Comment by pv** [comment]
archive.org had a copy of the blog list...
