### ISSUE TITLE
PDF of the Student's t-distribution

### ISSUE THREAD

**Issue by Alexander-Serov** [scipy/scipy.org#282]
I am not sure if it's the right place for the question, but why does the documentation on the page
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.t.html
feature \Gamma(\nu) in the PDF, while the real Student's distribution has \Gamma(\nu/2).
Is it a typo or a bug?

**Comment by pv** [comment]
It's a typo. Was fixed since then.

**Comment by pv** [comment]
Note that issues in the documentation of the projects should preferably be filed on the project's bug tracker, in this case https://github.com/scipy/scipy/issues

**Comment by Alexander-Serov** [comment]
Thanks!
Well, since I didn't know it was a typo, I couldn't know I should file there, right? :)
