### ISSUE TITLE
broken link to Py3K.txt

### ISSUE THREAD

**Issue by ynikitenko** [scipy/scipy.org#292]
On [Release Notes](https://docs.scipy.org/doc/numpy/release.html) page, the link to Python 3 support is broken:
http://projects.scipy.org/numpy/browser/trunk/doc/Py3K.txt (doesn't work, and is not archived on the web archive).

**Comment by ilayn** [comment]
That part belongs to a very old version release notes (1.5.0 we are now 1.16.3) from pre-Github times. You can use https://github.com/numpy/numpy/blob/master/doc/Py3K.rst.txt

**Comment by ynikitenko** [comment]
Thank you very much for the link! I needed that link to see the transition to Python 3, it was very interesting for me.
