### ISSUE TITLE
typo in and suggestions for SHGO docs

### ISSUE THREAD

**Issue by podkop** [scipy/scipy.org#295]
Page https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.shgo.html,
  the description of "constraints" argument ("constraints : dict or sequence of dict, optional"),
    2-nd line:
      g(x) <= 0 ...

Correct text: g(x) >= 0 ...

Explanation: the inequality constraints ("type": "ineq") are actually treated in the function as >= constraints. It is also confirmed in an example below on the same page (after the line "To demonstrate solving problems with non-linear constraints consider ...").

As a side note from a simple user: some phrases in the scipy docs are formally incorrect. 

For example, in the same description of the "constraints" argument we read: "Function(s) R\*\*n in the form:", while below we see the form of constraints, not just functions. 
Besides that, below we see _sets of constraints_, and corresponding vector-valued functions (R\*\*n -> R\*\*p), but then we read "Each constraint is defined..." (the singular form suggesting a _single_ constraint defined by a scalar function). In the example below, only single constraints are defined.

I would write something like following (assuming one can define a set of constraints at once):

Constraints definitions. A sequence where each element defines a set of constraints in either of the following forms: 
g(x) >= 0 defined by a function g : R^n -> R^m
h(x) == 0 defined by a function h : R^n -> R^p
Each system of constraints is defined in a dictionary with fields:
...

**Comment by rgommers** [comment]
There's a couple of suggestions here that @Stefan-Endres may want to incorporate in SHGO, so pinging him.

Thanks for the report @podkop. Note that the correct repo for SciPy documentation issues is https://github.com/scipy/scipy (this one is just for the top-level website), so please use that for future issues.

**Comment by Stefan-Endres** [comment]
Thank you very much @podkop for the detailed issue and @rgommers for pinging me. I'm almost ready to release a major performance update as well as a number of bug fixes in the [stand alone repository](https://github.com/stefan-endres/shgo), so I will include this doc fix [issue](https://github.com/Stefan-Endres/shgo/issues/29) and make a pull request to scipy with the latest version.

**Comment by rgommers** [comment]
Thanks @Stefan-Endres! 

I'll close this issue then, since you have one on your own repo.
