### ISSUE TITLE
Inconsistencies in "Citing"

### ISSUE THREAD

**Issue by adsche** [scipy/scipy.org#306]
Hi all,

the citing page lists the following entries (highlights from me):

> Jones E, **Oliphant E**, Peterson P, et al. SciPy: Open Source Scientific Tools for Python, 2001-, http://www.scipy.org/ [Online; accessed 2019-08-12].

> @Misc{,
>   author =    {Eric Jones and **Travis Oliphant** and Pearu Peterson and others},
>   title =     {{SciPy}: Open source scientific tools for {Python}},
>   year =      {2001--},
>   url = "http://www.scipy.org/",
>   note = {[Online; accessed <today>]}
> }

> **Travis E. Oliphant**. Python for Scientific Computing, Computing in Science & Engineering, 9, 10-20 (2007), DOI:10.1109/MCSE.2007.58 (publisher link)

And in the section NumPy

> **Travis E, Oliphant.** A guide to NumPy, USA: Trelgol Publishing, (2006).

You will notice that the name first name and initials Travis E Oliphant are inconsistent. In no. 4, first and last name are switched (compared to other references).

Cheers!

**Comment by mkg33** [comment]
Thanks, @adsche, we've improved the citing page.
