### ISSUE TITLE
Outdated information on mailing lists page

### ISSUE THREAD

**Issue by mattip** [scipy/scipy.org#308]
The information on `www/scipylab/mailing-lists.rst` as rendered [here](https://scipy.org/scipylib/mailing-lists.html) needs updating.

- Numpy-svn and Scipy-svn are no longer relevant
- Is nabble.com really the best we can offer for browsing the mailing lists?
- Is IRC still relevant or do we have a better chat alternative, or should we just remove that section?

**Comment by rgommers** [comment]
> Is nabble.com really the best we can offer for browsing the mailing lists?

Today, yes. It's possible to move the lists to Mailman 3 though (python.org mailman admins were trying this out a while ago) so we have a decent interface. Not sure what the status of that migration is.

> Is IRC still relevant or do we have a better chat alternative, or should we just remove that section?

There's a NumPy Gitter channel for users, and for people who wants to contribute there's a Slack (see https://www.numpy.org/devdocs/dev/index.html#contributing-to-numpy).

I'd like to use the same Slack style setup for contributing to SciPy.

**Comment by pv** [comment]
The IRC channel was discussed on the mailing list some years back and a number of people volunteered to manage it. AFAIK, they're still there and it's occasionally active, so there are at least no new reasons to drop it.

**Comment by mattip** [comment]
The information on the numpy nabble page was updated to the correct numpy-discussions@python.org domain (python not scipy) and website. Does the [scipy info](http://scipy-user.10969.n7.nabble.com/) need updating as well? I see some familiar names among the [admins](http://scipy-user.10969.n7.nabble.com/template/NamlServlet.jtp?macro=app_people&node=2), one of them (@rgommers ?) needs to login and go to the "options ->applications->mailing list archive settings"

**Comment by rgommers** [comment]
> needs to login and go to the "options ->applications->mailing list archive settings"

doesn't work. I can log in, but under options there's still only "Subscribe via email"

**Comment by pv** [comment]
I see only "Timmie" as admin. A mail address can be found, but it's been many years...

**Comment by jarrodmillman** [comment]
I believe this is fixed on the new site.
