### ISSUE TITLE
DOC: Update the license dates

### ISSUE THREAD

**Issue by mkg33** [scipy/scipy.org#322]
I'm currently working on removing any inconsistencies that are present on the website (i.e., punctuation, stylistic issues, etc.) and I just noticed the following (in `license.rst`):

```
=============
SciPy license
=============

| Copyright © 2001, 2002 Enthought, Inc.
| All rights reserved.
|
| Copyright © 2003-2013 SciPy Developers.
| All rights reserved.
```

Shall I update the end date in the range to 2019? Or is there a reason for keeping the year 2013?

**Comment by rgommers** [comment]
> Shall I update the end date in the range to 2019?

yes please! we'd like to keep that updated

**Comment by mkg33** [comment]
Done. Thanks for the quick reply!
