### ISSUE TITLE
Add Google Analytics?

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy.org#338]
One way of measuring impact and which functions are used frequently would be via website traffic. I'd be interested in setting up Google Analytics in order to collect that data. Based on [this](https://www.similarweb.com/website/scipy.org#overview) estimate of the number of hits scipy.org gets per month (~3 million), we wouldn't exceed the [traffic limit](https://support.google.com/analytics/answer/1070983?hl=en) for Google Analytics free version (10 million hit/month). [Setup](https://support.google.com/analytics/answer/1008015?hl=en) just requires adding the same snippet of code to the `<head>` of every page we want to track.

1. Shall I give this a shot?
2. Would the right place to add the code to this repo be an [`extrahead` block](https://www.sphinx-doc.org/en/master/templating.html) in [`layout.html`](https://github.com/scipy/scipy.org/blob/master/www/_templates/layout.html)?
2. Should this be added to scipy-sphinx-theme, too? Would adding the code directly to the `<head>` section of its [`layout.html`](https://github.com/scipy/scipy-sphinx-theme/blob/master/_theme/scipy/layout.html) make the code appear on every page?

**Comment by rgommers** [comment]
Better analytics would be useful, and Google Analytics seems fine (I have no experience with it though).

Re free limit, I think we're at that limit already. From your link: _Every user interaction can be sent to Analytics as an individual hit, including (but not limited to) each pageview, screenview, event, and ecommerce transaction. As a result, a single session can result in many hits._ SimilarWeb says 2.6 page visits per visitor. Also our user base is still growing fast, so numbers should go up further.

> which functions are used frequently

I suspect this is much easier to do via code analysis (e.g. https://github.com/Quansight-Labs/python-api-inspect). 

Google Analytics should probably be used at a higher level, like which scipy.org top-level pages are important, or tutorials vs refguide usage.

**Comment by ilayn** [comment]
This might have also a backlash though since most people don't want to be tracked and use adblockers and antitrackers (including myself). 

I don't have a strong opinion but google analytics seems like an overkill if just need a pagehit count.

**Comment by mattip** [comment]
Is scipy.org behind a service like cloudfare? I would imagine they can give basic page view statistics already.

**Comment by rgommers** [comment]
No it's not, and even if it were it'd be hard to get access to it (cause Enthought-owned).

**Comment by rgommers** [comment]
> I won't push much, but wouldn't one month of Tidelift pay for several years at $30/mo? (In fact, once interest rates recover, couldn't a month of Tidelift endow analytics in perpetuity?) A better website is more important, but they're not mutually exclusive.

Could you make this proposal on the core dev list, with what it would actually cost? That's where we decide on spending $$.

> Also, analytics would help us make our case when we apply for other money.

Yes, a number like that is useful for proposals. Although a typical total estimate like 1.5M/month would be all you need, so similarweb may be enough. 

> And it might be helpful to know how the website is used now to design a better site.

The current site is so bad and has so little useful content that I don't think this will help much.

**Comment by tupui** [comment]
Since https://github.com/scientific-python/scientific-python-hugo-theme/pull/89, we can ask to get added to the Scientific-Python project. Would this be ok?

**Comment by rgommers** [comment]
Sounds like a good idea to me!

**Comment by tupui** [comment]
@stefanv is this the Scientific-Python url that we have to use? If yes I can make a quick PR 😃

**Comment by stefanv** [comment]
Yeap, your PR #435 does the right thing! I've enabled scipy.org on our plausible install.

**Comment by tupui** [comment]
Do we want to have this for the documentation website? Which was the original idea of the issue.

**Comment by mdhaber** [comment]
Yes, please, I think. I'm not sure what data you get, but I was hoping to be able to see numbers for documentation of functions/classes so we can get a sense of what is being used.

**Comment by tupui** [comment]
This is what we get, no more but still valuable.

@stefanv if we want to add it to the documentation itself, I just need to copy the JS script right? Can we add this to the same dashboard (using the same domain in the config) or we need another one? Like can we do the following?

`<script defer data-domain="scipy.org" src="https://analytics.scientific-python.org/js/plausible.js"></script>`

<img width="1099" alt="Screenshot 2022-01-12 at 19 40 48" src="https://user-images.githubusercontent.com/23188539/149201971-1c31bbbd-8595-446c-bb74-bba99ece19a9.png">

**Comment by stefanv** [comment]
@tupui I don't think that will work, since the domains will be mis-matched. I've added `docs.scipy.org` as a separate data-domain. Once it starts tracking, I can add you as admin.

**Comment by stefanv** [comment]
Also, it looks like we'll be able to "roll up" those stats into one dashboard: https://github.com/plausible/analytics/discussions/160#discussioncomment-1581474

**Comment by stefanv** [comment]
@tupui It looks like you *can* use the same data-domain for both sites, it's just that the URLs will be combined: https://plausible.io/docs/plausible-script#can-i-use-the-same-snippet-across-my-domain-and-subdomain

The "rollup" mentioned above means you can track the sites separately *and* together, *or* together, *or* only separately. Let me know which option you prefer.

**Comment by tupui** [comment]
After reading this, I would say we start separately and if we need to combine things we can always add another domain to use the rollout method.

**Comment by stefanv** [comment]
Great, then you should be all set.
