### ISSUE TITLE
Contribution: new image edge detection technique

### ISSUE THREAD

**Issue by SujoyKG** [scipy/scipy.org#342]
Hello Sir/ Madam,

I want to contribute to SciPy (Python) with a new image edge
detection technique
[a-better-first-derivative-approach-for-edge-detection-IJERTV2IS110616.pdf](https://github.com/scipy/scipy.org/files/4527928/a-better-first-derivative-approach-for-edge-detection-IJERTV2IS110616.pdf)
 which is more generic & better than the similar popular
techniques for the same.
The paper that I have published is attached here with this email.
Please go through it.
If you like it, please tell me the process to move next.

Thanks & Regards,
Sujoy K Goswami
Principal Data Scientist
TVS Motor Company
India

**Comment by ilayn** [comment]
Hi @SujoyKG . Please first discuss this on the SciPy Dev mailing list. 

https://scipy.org/scipylib/mailing-lists.html

Also note that this repo is for scipy.org website. For SciPy related things choose Scipy repository.
