### ISSUE TITLE
Sphinx link in the footer returns HTP 400

### ISSUE THREAD

**Issue by stayen** [scipy/scipy.org#360]
The Sphinx link in the footer of scipy.org site, namely

http://sphinx.pocoo.org/

returns HTTP 400 (Nginx: 400 Bad Request).

**Comment by sethtroisi** [comment]
https://github.com/python/python-docs-theme/commit/fc9f203dd79587c8aed2b822cf7401518cd65bb5

**Comment by stayen** [comment]
It's changed in python-docs-theme, but isn't updated on the site?

**Comment by sethtroisi** [comment]
Sorry, that link was just to show what the change will probably look like (and that other people are making it). I added some context to my message.

**Comment by stayen** [comment]
@sethtroisi I see, thanks, so it's the matter of contacting the right people.

**Comment by rgommers** [comment]
Hmm I thought I fixed all of those. Too many Sphinx-based sites:( Let me have a look at this one.
