### ISSUE TITLE
Scipy logo vector file

### ISSUE THREAD

**Issue by mondeja** [scipy/scipy.org#373]
Hello. I'm looking for the original logo of Scipy in vector format (SVG or other vector format), in order to include it in the [simple-icons](https://github.com/simple-icons/simple-icons) project. I can see that you have included in this repository the icon in raster PNG format, but would be very useful if you can share the vector one. Could this be possible?

Thank you!

**Comment by grlee77** [comment]
There is an SVG version here:
https://github.com/scikit-image/skimage-branding/blob/master/logo/scipy.svg

It is probably also stored somewhere here under the SciPy org., but I don't know where offhand.

**Comment by mondeja** [comment]
Thank you!
