### ISSUE TITLE
Add a Footer containing link to all social media handles and mailing lists

### ISSUE THREAD

**Issue by Uttam-Singhh** [scipy/scipy.org#393]
Add a Footer containing links to all social media handles(we can use the logo of the particular handle) and link to mailing lists or any other important contact information.
Please assign me this if no one is working.

**Comment by tupui** [comment]
Hi, thanks for the proposal. I am not sure we want to do this. The website in general is pending (not started) an overhaul. So might not worth the effort of review/integration.

**Comment by Uttam-Singhh** [comment]
oh ok!
Please let me know!

**Comment by rgommers** [comment]
I agree, we're going to get rid of this theme and site layout, so it's not worth much effort. Also, we don't really have any social media anyway - only the mailing list, which is in the README on GitHub as well as on a separate page on the website.

Thanks for the offer of help though @Uttam-Singhh! I think once we get going on the website redesign, there'll be quite a bit to contribute to.

**Comment by Uttam-Singhh** [comment]
Oh ok sure!
Please let me know if there are any more opportunities for beginners...

**Comment by rgommers** [comment]
We're probably going to base the new site on the NumPy one (just tweak that design a bit and add new content), so if you'd want to try your hand at helping with the NumPy site, that would be great. The `good-first-issue` and `wimlds-sprint` labelled issues on https://github.com/numpy/numpy.org/issues are good starter issues.

**Comment by Uttam-Singhh** [comment]
Hello @rgommers, actually there are no `wimlds-sprint` issues and only 2 `good first` issues which are under process so please let me know if I can do something else.

**Comment by Uttam-Singhh** [comment]
@rgommers I have opened two issues on https://github.com/numpy/numpy.org/issues.
Can you please review and assign me those tasks. I'd would love to work on them.

**Comment by rgommers** [comment]
will do, thanks @Uttam-Singhh

**Comment by Uttam-Singhh** [comment]
Thank you so much @rgommers!
