### ISSUE TITLE
Scipy 1.7.0 release notes missing?

### ISSUE THREAD

**Issue by fasiha** [scipy/scipy.org#400]
Scipy versions [1.6.3](https://docs.scipy.org/doc/scipy/reference/release.1.6.3.html) and [1.7.1](https://docs.scipy.org/doc/scipy/reference/release.1.7.1.html) have valid release notes but when I click on the link in either of those pages for [1.7.0](https://docs.scipy.org/doc/scipy/reference/release.1.7.0.html), I get a 404 error?

I thought maybe it was a website caching issue but it's been like this for a few days now.

**Comment by tylerjereddy** [comment]
There are a few issues related to the new documentation theme we started using in the `1.7.x` series and how it interacts with our current release process.

One of a few related issues in the main repo: https://github.com/scipy/scipy/issues/14522

**Comment by tupui** [comment]
I believe this can be closed now.
