### ISSUE TITLE
Team galleries

### ISSUE THREAD

**Issue by jarrodmillman** [scipy/scipy.org#414]
After merging #413, consider adding team galleries.

**Comment by rgommers** [comment]
> Do we also need groups for the steering council and the release (or another name for people with secrets credentials, PyPi, etc.)?

Probably not - steering council overlaps largely with maintainers so a list of names in the governance docs will do. And release manager is named there too; usually one person rather than a team.

**Comment by tupui** [comment]
> > Do we also need groups for the steering council and the release (or another name for people with secrets credentials, PyPi, etc.)?
> 
> Probably not - steering council overlaps largely with maintainers so a list of names in the governance docs will do. And release manager is named there too; usually one person rather than a team.

👌 ok so we don't do a section for these 2 roles. Then let me know if you do some changes to the GH groups and I can run the scripts (and do a PR). I can also start with the single current maintainer list and I manually do the web one.

**Comment by rgommers** [comment]
I don't have much time this week (CZI workshop is happening), so maybe just go ahead with a PR so we see how it look and can review/tweak?

**Comment by jarrodmillman** [comment]
@tupui It may make sense to hold off on the script and stuff.  @stefanv and I are in the process of working on the team gallery stuff for the theme:  https://github.com/scientific-python/scientific-python-hugo-theme/pull/49

Take a look at https://github.com/scientific-python/scientific-python-hugo-theme/blob/main/tools/team_query.py.  We are trying to get a few other things fixed for the theme first, but we should have time to make a team gallery PR here next week.  If you have time, it would be great if you could help us with the general theme work.

We want to make one common solution, rather than having each project have to sort it out themselves.  Of course, I don't want to slow things down, though. ;)

**Comment by tupui** [comment]
> @tupui It may make sense to hold off on the script and stuff. @stefanv and I are in the process of working on the team gallery stuff for the theme: [scientific-python/scientific-python-hugo-theme#49](https://github.com/scientific-python/scientific-python-hugo-theme/pull/49)
> 
> Take a look at https://github.com/scientific-python/scientific-python-hugo-theme/blob/main/tools/team_query.py. We are trying to get a few other things fixed for the theme first, but we should have time to make a team gallery PR here next week. 

@jarrodmillman I just pushed a PR which uses this script. 

> If you have time, it would be great if you could help us with the general theme work.

I would be happy to help 😃 Just ping/email/call me.

> We want to make one common solution, rather than having each project have to sort it out themselves. Of course, I don't want to slow things down, though. ;)

Totally agree! There is no rush on my side, I thought the script was ready to use 😅

**Comment by rgommers** [comment]
I have renamed "Scipy core team" to "Maintainers", and also added an "Emeritus maintainers" team, currently containing 16 people who are no longer active. Before I remove anyone from the Maintainers team (causing them to lose a bunch of permissions) I'll ping those people and also discuss with the active maintainers what the permissions for Emeritus maintainers should look like.

Also, I made both teams visible, so anyone who is a member of the SciPy org is now able to see all members of each team and at-mention the team.

**Comment by tupui** [comment]
> I have renamed "Scipy core team" to "Maintainers", and also added an "Emeritus maintainers" team, currently containing 16 people who are no longer active. Before I remove anyone from the Maintainers team (causing them to lose a bunch of permissions) I'll ping those people and also discuss with the active maintainers what the permissions for Emeritus maintainers should look like.
> 
> 
> 
> Also, I made both teams visible, so anyone who is a member of the SciPy org is now able to see all members of each team and at-mention the team.

All sounds great to me. Thanks Ralf! I will update the PR after Christmas when I am back. This will let some time for people to reply to your emails.
