### ISSUE TITLE
Deploy new site

### ISSUE THREAD

**Issue by jarrodmillman** [scipy/scipy.org#418]
- [x] Merge #413
- [x] update DNS so that https://draft.scipy.org/ is served by netlify
- [x] add redirects (i.e., from `https://scipy.org/scipylib/<page>` to `https://scipy.org/<page>`)  #419
  - [x] `scipy.org/scipylib` ->  `scipy.org`
  - [x] `scipy.org/scipylib/license.html` -> `github.com/scipy/scipy/blob/master/LICENSE.txt`
  - [x] `scipy.org/scipylib/download.html` -> `scipy.org/download/`
  - [x] `scipy.org/scipylib/mailing-lists.html` -> `scipy.org/mailing-lists/`
  - [x] `scipy.org/scipylib/bug-report.html` -> `scipy.org/bug-report/`
  - [x] `scipy.org/scipylib/dev-zone.html` -> `scipy.org/dev-zone/`
  - [x] `scipy.org/scipylib/donations.html` -> `scipy.org/donations/`
  - [x] `scipy.org/scipylib/faq.html` -> `scipy.org/faq/`
- [x] update DNS so that https://scipy.org/ is served by netlify

A list of places that we need to update after making this change:
- [ ] https://github.com/scipy/scipy/blob/master/.github/FUNDING.yml
  -  https://github.com/scipy/scipy/pull/14960
- [ ] https://github.com/scipy/.github/blob/master/FUNDING.yml
  - https://github.com/scipy/.github/pull/1

**Comment by jarrodmillman** [comment]
@rgommers, @ilayn, @tupui We updated the DNS so that https://draft.scipy.org/ is served by netlify.  There are several cleanups I still want to do (e.g., updating the installation information, adding the team gallery, etc.).  But I think we should deploy what we have now soon.  So it would be great if you could let us know:

1. If there is anything else we need to do before updating the DNS so that https://scipy.org/ is served by netlify.
2. If there are any other old links we should redirect.
3. If there are any other places we will need to update after making the DNS change.

Also are there any specific times we should avoid making this change?

**Comment by tupui** [comment]
Thanks for doing this. I also think we can deploy as is. It's already in good/better shape compared to the current site.

**Comment by rgommers** [comment]
I agree, +1 for going ahead. There are no specific times to avoid, please pick whatever is most convenient for you.

**Comment by jarrodmillman** [comment]
@rgommers, @ilayn, @tupui We've updated the DNS.  You should now (or very soon) see the new site when you go to https://scipy.org (or https://www.scipy.org).  Please let us know if you see any problems.

**Comment by mdhaber** [comment]
Looks great!

**Comment by ilayn** [comment]
Fantastic! Thanks so much again for this effort.
