### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by jarrodmillman** [scipy/scipy.org#420]
See
- https://numfocus.salsalabs.org/donate-to-scipy/index.html
- https://numfocus.org/project/scipy
- https://github.com/scipy

**Comment by tupui** [comment]
Also in the readme?

**Comment by rgommers** [comment]
Changed in the main repo, and on the GitHub org as well.

**Comment by tupui** [comment]
We can close this, AFAICT all logos are updated now.
