### ISSUE TITLE
DOC: process for new releases

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy.org#422]
Hi @stefanv and @jarrodmillman -- can you briefly summarize what I need to do to announce a new release with the new `scipy.org`? The old process is like this PR: https://github.com/scipy/scipy.org/pull/399

Once I learn it I can just repeat the PRs with a bumped version I suspect.

**Comment by tylerjereddy** [comment]
It may be obvious, but it is pretty late so I'll take a look later this weekend.

**Comment by stefanv** [comment]
Hi Tyler, I can follow up with more detail tomorrow, but I believe you want to update https://github.com/scipy/scipy.org/blob/master/content/en/news.md

The website, after merge, will build and deploy itself.

**Comment by rgommers** [comment]
The second place to update is the `news:` entry in `config.yaml` in the root of the repo.

**Comment by stefanv** [comment]
Ah, right, that sets the news bar text on the front page!

**Comment by stefanv** [comment]
In our other sites, I think we will have the news articles automatically list themselves and then use the latest one on the banner.  That way, only a new entry has to be added as a markdown file.

I'll implement that in the theme, and then we can decide if we want to switch SciPy over.

**Comment by stefanv** [comment]
See https://github.com/scientific-python/scientific-python-hugo-theme/pull/64

**Comment by tupui** [comment]
Following #425, we can continue to have a single news page and we have now the possibility to update the banner from the news preamble. Hence making a new release (or any news) would just mean updating the news page and preamble.

**Comment by jarrodmillman** [comment]
@tylerjereddy We are still changing things a bit, so feel free to ping me when you make a new release announcement PR and I will double-check that you got everything.  Also, if you point me to the scipy release process documentation, I will make sure to keep it up-to-date.

**Comment by tupui** [comment]
@jarrodmillman AFAIK the release documentation is here https://scipy.github.io/devdocs/dev/core-dev/index.html#making-a-scipy-release

**Comment by tupui** [comment]
I believe this is resolved now.
