### ISSUE TITLE
Search URL breaks on some paths of the docs subdomain

### ISSUE THREAD

**Issue by kwinkunks** [scipy/scipy.org#429]
I am not sure where exactly this bug originates, or even if it would be called a bug as such. I tried searching the scipy.org repo and the scipy docs, but I'm not smart enough to find the code that's doing this.

Here's what I'm doing:

- Google 'scipy generic filter' (that's how I generally get to the docs, I know it's not a great approach!)
- First link: https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.ndimage.filters.generic_filter.html
- Now: 
  - EITHER click on the **this page** link
  - OR click on the **documentation of the latest stable release** link and search
- Neither works, because of the `reference` bit in the URL: https://docs.scipy.org/doc/scipy/reference/search.html?q=scipy.ndimage.filters.generic_filter

This link does work: https://docs.scipy.org/doc/scipy/search.html?q=scipy.ndimage.filters.generic_filter

I realize the correct link to the current docs is offered by Google as the next related link, but perhaps this is affecting others too?

**Comment by rgommers** [comment]
Thanks for the report @kwinkunks. Yes, this is known problem. We should fix it by having a version switcher in the docs, and always defaulting to latest. Plus some robots indexing magic perhaps. The version switcher is planned, but is a nontrivial feature. I expect it to arrive within the next months.

**Comment by tupui** [comment]
FYI they just merged the feature on the theme side 😃 so we might be able to enable this soon.

**Comment by lucascolley** [comment]
this is fixed now!
