### ISSUE TITLE
Installation instructions lacking

### ISSUE THREAD

**Issue by stefanv** [scipy/scipy.org#436]
Currently, the scipy README refers to https://www.scipy.org/install/ as the most up-to-date source of source installation instructions.

However, that page only says:

> SOURCE PACKAGES
> You can build any of the packages from source. Those involved in development may take this route to get developmental versions or alter source code. Refer to individual projects for more details.

This is not very helpful.

**Comment by rgommers** [comment]
That's because this was the SciPy ecosystem install page. We should just link to the docs.

When we're updating, let's also fix the rest. It was pointed out earlier today that conda-forge/miniforge/mambaforge are not mentioned at all. I'd say Mambaforge is my first recommendation these days.

**Comment by stefanv** [comment]
I am trying to build SciPy, and am unable to do so. I feel like a complete n00b :joy:

Just a cryptic:

```
  FileNotFoundError: [Errno 2] No such file or directory: '/home/stefan/src/scipy/scipy/_lib/highs/CMakeLists.txt'
```

So, maybe we also need some instruction updates related to the meson build process?

**Comment by stefanv** [comment]
The [dev docs also say](http://scipy.github.io/devdocs/install_upgrade.html#installing-upgrading):

> Information on how to install SciPy and/or the SciPy Stack (a larger set of packages for scientific computing with Python) can be found at https://scipy.org/install/.

**Comment by ev-br** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: '/home/stefan/src/scipy/scipy/_lib/highs/CMakeLists.txt'

Just seen it a couple of days back, with a regular setup. py build. Felt just the same :-). 
I *think* it's fixed by git submodule update

**Comment by rgommers** [comment]
`git submodule update --init` should fix that one.

**Comment by rgommers** [comment]
> So, maybe we also need to link to [instruction updates related to the meson build process](http://scipy.github.io/devdocs/dev/contributor/meson.html)?

Not yet, since it's not very well tested yet and is only 100% robust on Linux + OpenBLAS at the moment. Give it 3 more months.

**Comment by tupui** [comment]
Re mamba, this is so great! I started using this last week and cannot go back to something else!!

**Comment by rgommers** [comment]
> Do you mean that we should link `/install` to `https://scipy.github.io/devdocs/getting_started.html`?

No, just for "building from source" to link to https://scipy.github.io/devdocs/dev/contributor/contributor_toc.html#development-environment. Our website should have the main advice. Building from source is niche now (and as difficult as ever still), and should not be presented on scipy.org to the average user.

**Comment by tupui** [comment]
This is actually fixed and I think the page is in good shape now. Closing.
