### ISSUE TITLE
Harmonize contribute pages from numpy.org and scipy.org

### ISSUE THREAD

**Issue by stefanv** [scipy/scipy.org#446]

**Comment by tupui** [comment]
What do you have in mind? I updated the this website to be close to what NumPy has.

**Comment by stefanv** [comment]
The NumPy page recently received an update, so just wanted to por that.

**Comment by tupui** [comment]
You are talking about this one right https://numpy.org/contribute/ ? Because that was my model for https://scipy.org/contribute/. I just removed the part about slack.

**Comment by stefanv** [comment]
Yes, Jarrod recently made a commit.

**Comment by jarrodmillman** [comment]
Making a PR as we speak.
