### ISSUE TITLE
Broken Link to Governance 

### ISSUE THREAD

**Issue by noatamir** [scipy/scipy.org#464]
When clicking on scipy.org/about I get redirected to ->
    https://scipy.github.io/devdocs/dev/governance/governance.html
which displays a 404 file not found github error page.  (using both chromium and firefox)

This might be a SciPy documentation issue as it seems like the scipy/doc/scource/dev/governance.rst file is a part of the documentation. But since I didn't have any code to reproduce the error I opened the issue here after all. I hope that's ok?!

**Comment by tupui** [comment]
Thanks @noatamir! Do you want to fix it?

**Comment by noatamir** [comment]
Sure! Let me give it a go... ^_^

**Comment by NaincyKumariKnoldus** [comment]
Hey @noatamir I had loved to fixed this. And raised PR. Please review that.
