### ISSUE TITLE
a sentence in stats.norm's docstring seems incorrect

### ISSUE THREAD

**Issue by clwez** [scipy/scipy.org#471]

**Comment by clwez** [comment]
Specifically, ``norm.pdf(x, loc, scale)`` is identically equivalent to ``norm.pdf(y) / scale`` with ``y = (x - loc) / scale``.  Here,'pdf' should be cdf.

**Comment by ilayn** [comment]
Thanks @clwez this repo is for the website and it's related machinery. Please use the SciPy repo for the content.

https://github.com/scipy/scipy/issues
