### ISSUE TITLE
TLS certificate has expired on docs.scipy.org 

### ISSUE THREAD

**Issue by jorenham** [scipy/scipy.org#542]
It apparantly expired on 15-11-2023.

**Comment by andyfaff** [comment]
See https://github.com/scipy/docs.scipy.org/issues/80#issuecomment-1813688181

**Comment by mdhaber** [comment]
@tylerjereddy I think there is still an issue with https://projects.scipy.org/scipylib/mailing-lists.html

**Comment by lucascolley** [comment]
this was fixed https://github.com/scipy/docs.scipy.org/issues/80#issuecomment-1845142651
