### ISSUE TITLE
Intersphinx objects.inv SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by pllim** [scipy/scipy.org#544]
Hello! Since last night, I encountered the following error when trying to pull in scipy doc via intersphinx on ReadTheDocs:

intersphinx inventory 'https://docs.scipy.org/doc/scipy/objects.inv' not fetchable due to <class 'requests.exceptions.SSLError'>: HTTPSConnectionPool(host='docs.scipy.org', port=443): Max retries exceeded with url: /doc/scipy/objects.inv (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1006)')))

I do not see this error when fetching https://docs.scipy.org/doc/scipy/objects.inv from local browser, just on ReadTheDocs.

Any help would be greatly appreciated. Thanks!

Also see: https://github.com/astropy/astropy/issues/15624 and https://readthedocs.org/projects/astropy/builds/22573456/

**Comment by ilayn** [comment]
A few hours ago, the certificate is renewed could you please try again?

**Comment by pllim** [comment]
Seems to work now. Thanks!
