### ISSUE TITLE
.keyfeatures-box-text issue | PR in theme opened

### ISSUE THREAD

**Issue by ApoB-100** [scipy/scipy.org#547]
As there seems to be a slight glitch in the CSS on scipy.org (see screenshots below), there is a PR open in the theme repo, should correct the issue. See: [Open PR](https://github.com/scientific-python/scientific-python-hugo-theme/pull/431) 

Changed the height of .keyfeatures-box-text from a fixed 6em to auto to accomodate longer texts. The box height now depends on the longest text in each row. See the issue on the scipy.org main page or the top screenshot attached. ("Enjoy the flexibility of Python with the speed of[...]" & "SciPy provides algorithms for
optimization, integration, interpolation, eigenvalue problems, algebraic equations, differential equations,[...]") The bottom screenshot shows the scipy.org website with the "auto" patch.
![image](https://github.com/scipy/scipy.org/assets/79815526/51e80d09-cbe2-4212-9d4b-b9c8633a5755)
![image](https://github.com/scipy/scipy.org/assets/79815526/decb6e9f-b79a-4aab-b4fc-a4da8a4b47f7)

**Comment by jarrodmillman** [comment]
See #548.
