### ISSUE TITLE
dev docs not updated since ~4 months

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy.org#67]
I was looking for 'differential evolution' docs on
http://docs.scipy.org/doc/scipy-dev/reference/optimize.html
but these dev docs appear to not have been updated since March 16.  If someone has time, could the website possibly be updated to reflect, for example, the changes to https://github.com/scipy/scipy/blob/master/scipy/optimize/__init__.py over the last few months?

**Comment by rgommers** [comment]
up-to-date at the moment, so closing.
