### ISSUE TITLE
Wiki and blogs are down

### ISSUE THREAD

**Issue by jondo** [scipy/scipy.org#85]
Currently, neither http://wiki.scipy.org/ nor http://planet.scipy.org/ can be accessed.

**Comment by takluyver** [comment]
Thanks for the heads up. I have pinged people at Enthought to hopefully get it fixed.

I wish I knew what the underlying problem is - the server hosting those sites has been doing this for years.

**Comment by rgommers** [comment]
fixed again. thanks for the report @jondo and the quick follow-up @takluyver

**Comment by danielgeier** [comment]
Sites are down again and have been for a few days.

**Comment by filipesaraiva** [comment]
It is down yet! :(
