### ISSUE TITLE
error in site documentation for pmf() method for Poisson distribution

### ISSUE THREAD

**Issue by romunov** [scipy/scipy.org#87]
[Probability mass function method (`pmf`) for Poisson distribution](http://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.poisson.html#scipy.stats.poisson) claims first argument to be `x`, whereas the actual argument is `k`, as evident in

```
>>> help(poisson.pmf)
Help on method pmf in module scipy.stats._distn_infrastructure:

pmf(self, k, *args, **kwds) method of scipy.stats._discrete_distns.poisson_gen instance
    Probability mass function at k of the given RV.
    
    Parameters
    ----------
    k : array_like
        quantiles
```

**Comment by ev-br** [comment]
Thanks for the report, but this should be filed under https://github.com/scipy/scipy --- this documentation is autogenerated in https://github.com/scipy/scipy/blob/master/scipy/stats/_distn_infrastructure.py .

A relevant scipy PR is https://github.com/scipy/scipy/pull/4499, comments welcome.

I'm thus closing this issue.

**Comment by romunov** [comment]
It would appear I have misread  the documentation [on bug reportin](http://www.scipy.org/bug-report.html). I understood "above tracker" as [https://github.com/scipy/scipy.org/issues](https://github.com/scipy/scipy.org/issues) and didn't realize it refers to the list above that text. Sorry to inconvenience you, I will take my business to the appropriate tracker.

**Comment by ev-br** [comment]
@romunov A PR with better wording would be welcome as well :-)
