### ISSUE TITLE
mstats.mannwhitneyu and stats.mannwhitneyu return inconsistent pvalues

### ISSUE THREAD

**Issue by cshowe** [scipy/scipy.org#89]
Assuming sample_population and base_population are masked arrays:

mstats.mannwhitneyu(sample_population, base_population)

and

stats.mannwhitneyu(sample_population.compressed(), base_population.compressed())

Return the same mann-whitney statistic but differing p-values.  The pvalue from mstats is twice the pvalue from stats suggesting that the mstats implementation is returning a 2 sided pvalue while the stats implementation returns the 1-sided pvalue - but there's nothing in the scipy documentation to indicate that this is the case.

**Comment by pv** [comment]
Moved to the scipy library issue tracker https://github.com/scipy/scipy/issues/4641 (documentation issues, as opposed to website issues, go there)
