### ISSUE TITLE
mismatch between doc an source  code of optimize.leastsq

### ISSUE THREAD

**Issue by scimax** [scipy/scipy.org#90]
http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.optimize.leastsq.html#scipy.optimize.leastsq

For the parameter "maxfev" it is written that is is set to `100*(N+1)` if unspecified. In the source code it is either set to `200*(n + 1)` in case of "Dfun is None" or to `100*(n + 1)` in the case of given "Dfun"

**Comment by rgommers** [comment]
@scimax thanks for the report. This should be fixed by https://github.com/scipy/scipy/pull/4758. 

Note that the right repo to report issues on next time for Scipy documentation is https://github.com/scipy/scipy instead of https://github.com/scipy/scipy.org
