### ISSUE TITLE
mail, wiki, and blogs are down

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy.org#94]
http://wiki.scipy.org/
http://planet.scipy.org/
http://mail.scipy.org/

**Comment by takluyver** [comment]
:angry: I'll ping the people who maintain it. Again...

**Comment by takluyver** [comment]
(thanks for pointing it out)

**Comment by takluyver** [comment]
The sites are back now. They're looking for a fix to stop this from happening repeatedly.

**Comment by argriffing** [comment]
I think these are down again.

**Comment by takluyver** [comment]
They seem to be working from here at the moment.

**Comment by argriffing** [comment]
ping again... `It's not just you! http://mail.scipy.org looks down from here.`

**Comment by takluyver** [comment]
I see it too. I've pinged people by email.
