### ISSUE TITLE
Trouble using bioread to convert files from .acq to .mat

### ISSUE THREAD

**Issue by 2puppies** [scipy/scipy.org#95]
Hello,

I am a new Python user (2.7.10) attempting to use bioread (https://pypi.python.org/pypi/bioread/0.9.5) to convert files from aqknowledge to matlab. I am using a 64-bit PC, and I have downloaded Matlab, Python, numpy, scipy and bioread. Can someone walk me through the installation process for this package? I can't seem to get it to work.

Thank you so much for your help!!

**Comment by pv** [comment]
You should contact the bioread authors for help with their software. This issue tracker is for issues on the scipy.org web pages (broken links etc.).
