### ISSUE TITLE
List of Scikits 404

### ISSUE THREAD

**Issue by louisel** [scipy/scipy.org#98]
scikits.appspot.com returns 404, so the list of scikits (scikits.appspot.com/scikits) cannot be accessed.

**Comment by pv** [comment]
Seems to be down. In the meanwhile, you can use
https://pypi.python.org/pypi?%3Aaction=search&term=scikit&submit=search

**Comment by takluyver** [comment]
If it was set up as an AppEngine App using the old data store model, Google may have turned it off - I've been getting emails for a few months about transitioning some old applications I made on AppEngine to a new database system, and there was a cutoff date where apps left on the old system would be killed.

I don't know:

- Who maintained that site?
- Do we still want a site listing scikits? I feel like it was a good idea, but only a handful really took off, and perhaps it's not worth having a dedicated site to list them.
- If we do, do we want it on Appengine? I think that a static site on Github pages or something would be easier to maintain.

**Comment by louisel** [comment]
Based on the [wayback machine's archive](https://web.archive.org/web/20150430213147/https://scikits.appspot.com/scikits) of the website, it appears that most of the info is duplicated on pypi. Would a static page pointing to the respective pypi pages suffice?

**Comment by rgommers** [comment]
I agree that a static page which lists scikits + an explanation of what a scikit is (updated version of "about scikits") under scipy.org is enough. The automated listing feature on the appspot site doesn't add too much.

**Comment by rgommers** [comment]
An update of http://scipy.org/about.html and a separate section on http://scipy.org/topical-software.html may be enough.

**Comment by rgommers** [comment]
@louisel would you be interested in sending a PR to fix this?

**Comment by pv** [comment]
I think @stefanv had fixing the appspot app somewhere in the priority
queue, probably not at the top though :)

**Comment by louisel** [comment]
Ok, I'll send a PR for a static page while the appspot app gets fixed.

**Comment by stefanv** [comment]
I've started the app migration--should be done in an hour or so.
